grids:
- type: plane
  coord:
  - 8
  - 10
  - 0
  magic_factory:
  - symbol: 0
    coord:
    - 3
    - 4
  - symbol: 1
    coord:
    - 3
    - 5
  - symbol: 2
    coord:
    - 4
    - 4
  - symbol: 3
    coord:
    - 4
    - 5
  qubit:
  - symbol: 0
    coord:
    - 4
    - 2
  - symbol: 1
    coord:
    - 6
    - 4
  - symbol: 2
    coord:
    - 6
    - 6
  - symbol: 3
    coord:
    - 4
    - 7
  - symbol: 4
    coord:
    - 2
    - 2
  - symbol: 5
    coord:
    - 4
    - 0
  - symbol: 6
    coord:
    - 2
    - 0
  - symbol: 7
    coord:
    - 0
    - 6
  - symbol: 8
    coord:
    - 2
    - 7
  - symbol: 9
    coord:
    - 0
    - 4
  - symbol: 10
    coord:
    - 6
    - 8
  - symbol: 11
    coord:
    - 4
    - 9
  - symbol: 12
    coord:
    - 0
    - 2
  - symbol: 13
    coord:
    - 2
    - 9
  - symbol: 14
    coord:
    - 6
    - 2
