grids:
- type: plane
  coord:
  - 8
  - 8
  - 0
  magic_factory:
  - symbol: 0
    coord:
    - 3
    - 3
  - symbol: 1
    coord:
    - 3
    - 4
  - symbol: 2
    coord:
    - 4
    - 3
  - symbol: 3
    coord:
    - 4
    - 4
