grids:
- type: plane
  coord:
  - 10
  - 10
  - 0
  magic_factory:
  - symbol: 0
    coord:
    - 0
    - 4
  - symbol: 1
    coord:
    - 0
    - 6
  entanglement_factory:
  - symbol: 0
    pair: 1
    coord:
    - 0
    - 0
  qubit:
  - symbol: 0
    coord:
    - 3
    - 2
  - symbol: 1
    coord:
    - 4
    - 4
  - symbol: 2
    coord:
    - 6
    - 4
  - symbol: 3
    coord:
    - 4
    - 6
  - symbol: 4
    coord:
    - 6
    - 6
  - symbol: 5
    coord:
    - 3
    - 8
  - symbol: 14
    coord:
    - 7
    - 2
- type: plane
  coord:
  - 10
  - 10
  - 2
  magic_factory:
  - symbol: 2
    coord:
    - 0
    - 4
  - symbol: 3
    coord:
    - 0
    - 6
  entanglement_factory:
  - symbol: 1
    pair: 0
    coord:
    - 0
    - 0
  qubit:
  - symbol: 6
    coord:
    - 3
    - 8
  - symbol: 7
    coord:
    - 6
    - 6
  - symbol: 8
    coord:
    - 6
    - 4
  - symbol: 9
    coord:
    - 4
    - 4
  - symbol: 10
    coord:
    - 3
    - 2
  - symbol: 11
    coord:
    - 7
    - 2
  - symbol: 12
    coord:
    - 4
    - 6
  - symbol: 13
    coord:
    - 7
    - 8
